//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanky1
    {
        public int Id { get; set; }
        public string Autor { get; set; }
        public string Text { get; set; }
        public string Datum { get; set; }
        public string Nazev { get; set; }
    }
}
